### ISSUE TITLE
Not able to build the project

### ISSUE THREAD

**Issue by AkashDeepKaushik** [microsec/MscSCEP#1]
Hi 
I downloaded the code and tried to build but build keeps failing. Can you please provide steps on how to setup the project. I downloaded all the dependency project and added reference to them but still no luck.
Can you please help.

**Comment by microsec** [comment]
Dear @AkashDeepKaushik !
Unfortunately this project has been long abandoned and is not supported anymore. We have a replacement project for our internal use that can be made commercially available upon request. Please contact sales@microsec.hu if you are still interested.
Sorry for misleading you!
